### ISSUE TITLE
Meetup #5 content (2018-10-11)

### ISSUE THREAD

**Issue by ErichDonGubler** [utah-rust/utah-rust.github.io#17]
Meetup link: https://www.meetup.com/utahrust/events/255209633/
Utah Rust site link: -

## Current agenda

Hosted at Jane's Thanksgiving Point location (see Meetup link above).

 - 7-8 PM (1 hr.): Going over Rust 2018 (https://github.com/utah-rust/utah-rust.github.io/issues/21) would be fantastic. @CleanCut and @pinealservo will be leading this discussion.
 - 8-9 PM (1 hr.): open discussion.

## Todos

- [ ] Create a new event page stub for this event
- [x] Confirm venue (Jane)
- Add content to agenda here
    ~~- [ ] @beatgammit has volunteered to do something this time -- does that still work? Maybe:
        -  Intro to WebAssembly with Rust (#14)
        - Actix actor framework + `actix-web` (#15)~~
    - [x] Going over Rust 2018 (https://github.com/utah-rust/utah-rust.github.io/issues/21) would be fantastic. Taken by @CleanCut and @pinealservo.
- [ ] ~~Upload any videos recorded~~
- [x] Edit meetup page

**Comment by adorton** [comment]
Can we annotate these planning issues with the proposed month (and date if we're firm on a specific date)?

**Comment by epage** [comment]
I'd volunteer to speak but I don't want people to get tired of me.  If someone wants mentoring on a topic so you can feel more confident to present on it instead of me, I'm willing to do so.

**Comment by TomPridham** [comment]
My company(Jane) is willing to host again.

**Comment by ErichDonGubler** [comment]
Pinging @beatgammit here again, just in case the original issue didn't -- not sure how Github handles that.

**Comment by ErichDonGubler** [comment]
@TomPridham: Wooot! Thank you!

**Comment by CleanCut** [comment]
@TomPridham Thanks for having Jane host!  Last time I made it to the meeting (which was also at Jane) there was food there. Is that going to be the case again?  To be clear, I don't think that's any sort of expectation that there has to be food provided (that I'm aware of), but if there is going to be food the it would be great to include that in the announcement so that people can plan accordingly.  Either way, I appreciate the folks/businesses willing to host these sorts of things! ❤️

**Comment by ErichDonGubler** [comment]
@CleanCut: I don't currently have any expectation of food, though I didn't last time and there WAS food. @TomPridham?

**Comment by TomPridham** [comment]
There will be food =)

**Comment by CleanCut** [comment]
Rock on. This is the best user group, ever. 😉

**Comment by TomPridham** [comment]
@CleanCut @ErichDonGubler is 9 still the expected turnout? I'm going off the meetup page, but wanted to make sure we got enough food for everyone if there were rsvps not on there

**Comment by ErichDonGubler** [comment]
@TomPridham: Food for about 12 should be good at the rate we're going -- not everyone eats, but some people (like me) eat more than one helping. :P

If it helps at all, every time before food has been left over.

**Comment by beatgammit** [comment]
Sorry, I wanted to present about something like this, but I just can't make it. Life is complicated and whatnot.

I'm looking forward to coming next month though to watch, and hopefully present at some point in the future.

**Comment by CleanCut** [comment]
@beatgammit No worries!  We'll look forward to seeing you next month.

**Comment by CleanCut** [comment]
Thanks for an awesome meeting, everyone! 

We can probably close this issue, now. ;-)

**Comment by ErichDonGubler** [comment]
@CleanCut: I just want to tackle the "Create a new event page stub for this event", and then I'll close it!
