### ISSUE TITLE
Meetup #6 content (2018-11-08)

### ISSUE THREAD

**Issue by ErichDonGubler** [utah-rust/utah-rust.github.io#18]
~~Meetup link: https://www.meetup.com/utahrust/events/255209655/~~
~~Utah Rust site link: -~~

## ~~Current agenda~~

~~Currently free and a *blue sky* both for venue and content. Comment here if you want to contribute!~~

## ~~Todos~~

- [ ] ~~Create a new event page stub for this event~~
- [ ] ~~Confirm venue~~
- [ ] ~~Add content to agenda here~~
- [ ] ~~Upload any videos any videos~~
- [ ] ~~Edit meetup page with assets generated from meetup~~

**Comment by ErichDonGubler** [comment]
This meetup was cancelled, so I'm going to close this.
