### ISSUE TITLE
Meetup #7 content (2018-12-13)

### ISSUE THREAD

**Issue by ErichDonGubler** [utah-rust/utah-rust.github.io#19]
Meetup link: https://www.meetup.com/utahrust/events/255209738/
Utah Rust site link: -

## Current agenda: Rust in 2018 and 2019

**Location**: Will be hosted at Pyrofex.

Currently free and a *blue sky* both content. Comment here if you want to contribute!

### Ideas

* We've [some ideas for an official logo](https://github.com/utah-rust/logo/issues/1)!
* This year of Rust in review -- so much has happened!
* Rust 2019: call for blog posts

## Todos

- [x] Create a new event page stub for this event
- [x] Make sure that the TWiR calendar has the Meetup link
- [x] Confirm venue
    - [x] ~~*Food at venue?*~~ Light snacks.
    - [x] ~~*Recording at venue?*~~ Yes!
- [x] Add content to agenda here
- [x] Upload any videos any videos
- [x] Edit meetup page with assets generated from meetup

**Comment by ErichDonGubler** [comment]
@epage, it's been a while since you've presented -- were you interested? Don't feel like you've dominated the meetups too much! 😃

**Comment by epage** [comment]
My plan was to skip this meeting because of our newborn but I can check with my wife if I'm needed.

**Comment by ErichDonGubler** [comment]
@epage: If it's a question of being there for your baby, then *be the daddy you want to be*. :) We can make do!

In the meantime, I'll try to compile the cool stuff that's happened in Rust this year -- mind if I PM you the tentative slides I have to see if I missed anything (once I have them)?

**Comment by epage** [comment]
> If it's a question of being there for your baby, then be the daddy you want to be. :) We can make do without you for a meetup!

My daughter is doing fine; supporting my wife is my priority.

> In the meantime, I'll try to compile the cool stuff that's happened in Rust this year -- mind if I PM you the tentative slides I have to see if I missed anything (once I have them)?

Sure

**Comment by epage** [comment]
Something else that might be timely is to give example of rust2019 posts and encouraging people to post their ideas to the community, with workshopping of the ideas if people need them.
