### ISSUE TITLE
Meetup #8 content

### ISSUE THREAD

**Issue by ErichDonGubler** [utah-rust/utah-rust.github.io#20]
## Current agenda

Currently free and a *blue sky* both for venue and content. Comment here if you want to contribute!

## Todos

- [ ] Create a new event page stub for this event
- [ ] Confirm venue
- [ ] Add content to agenda here
- [ ] Upload any videos any videos
- [ ] Edit meetup page with assets generated from meetup

**Comment by epage** [comment]
I'll be covering error reporting in Rust, from the basics to best practices

https://github.com/utah-rust/utah-rust.github.io/issues/1

**Comment by ErichDonGubler** [comment]
@epage: How much time were you thinking?

**Comment by ErichDonGubler** [comment]
@glademiller: If you want to make an issue with more details about your talk, feel free, but for this issue all I need is:

* Name of your presentation
* The amount of time you want to present.

**Comment by glademiller** [comment]
Name: Rust for MicroServices with Actix Web
Time: ??? I'm not sure yet I would say at least 10 minutes but I could imagine going longer.

**Comment by ErichDonGubler** [comment]
@glademiller: We could allocate you 20 minutes, and say that there's NO pressure to fill up the whole thing. :) What do you think?

**Comment by glademiller** [comment]
Sounds like a plan

**Comment by ErichDonGubler** [comment]
@coolaj86 was thinking of doing some introduction to Neon, though I'm not sure if it will fit with the presentations we already have. I'm pinging him to let him know we can all collaborate here. :)

**Comment by coolaj86** [comment]
I just saw TBD, so I made the suggestion. If you’ve got other topics I’d rather save it for another time.

**Comment by anderspitman** [comment]
I've been stuck for a couple days on a closure borrowing problem. I think I just need someone more experienced in Rust to talk it over with. Anyone open to meeting early or staying a bit after to take a look at it?

**Comment by epage** [comment]
Sure!

**Comment by ErichDonGubler** [comment]
@anderspitman: Absolutely! :)

**Comment by anderspitman** [comment]
Awesome, thanks! I'm assuming after is better, but I'm flexible. What works for you guys?

**Comment by epage** [comment]
My presentation: https://epage.github.io/talks/2019/01/dont-panic/

**Comment by ErichDonGubler** [comment]
@glademiller, got any slides you can link us?

**Comment by ErichDonGubler** [comment]
@TomPridham will let us know where to either upload or link to video(s). Tom, I'm more than happy to do video editing if you need me to!
