### ISSUE TITLE
Meetup #9 content (2019-02-12)

### ISSUE THREAD

**Issue by ErichDonGubler** [utah-rust/utah-rust.github.io#22]
Meetup link: https://www.meetup.com/utahrust/events/257819656
Utah Rust site link: -

## Current agenda

Will be hosted at [InsideSales in Provo](https://www.google.com/maps/search/?api=1&query=40.211520%2C-111.653650).

* Vivint (one of our hosts) and a certain meetup member are both looking for some Rust-related work!
* Re-hashing the logo: anybody feel strongly one way or the other?
* @coolaj86 will be giving an introductory presentation on [Neon](https://github.com/neon-bindings/neon).
* @anderspitman will be presenting on an FFI project of his.

## Todos

- [x] Make sure that the TWiR calendar has the Meetup link
- [ ] Create a new event page stub for this event
- [x] Confirm venue
    - [x] ~~Food at venue?~~ Yes, pizza!
    - [x] ~~Recording at venue?~~ Yes!
- [x] Ideas?
- [x] Confirm ideas in agenda
- [x] Have the meetup!
- [ ] Edit Utah Rust page with assets generated from meetup
    - [x] Outline agenda content: speakers, presentations
    - [ ] Link slides
        - [x] @anderspitman's presentation
        - [ ] @solderjs's presentation
    - [ ] Upload and link any videos recorded (@erichdongubler: Do the editing!)
        - [ ] @anderspitman's presentation
        - [ ] @solderjs's presentation

**Comment by ErichDonGubler** [comment]
@beatgammit: I know you've said that you've wanted to present on web stuff...maybe February is enough notice? ;)

**Comment by ErichDonGubler** [comment]
Hmm...Perhaps Tuesday would be better?

**Comment by anderspitman** [comment]
@coolaj86 are you still planning on talking about Neon? I was planning to do a lightning talk on a little FFI project I did last week. I'll probably include a node example so these could go well together.

**Comment by ErichDonGubler** [comment]
@anderspitman, are you still good for presenting on Tuesday?

**Comment by coolaj86** [comment]
Yeah, I’ll give Neon a run through.

**Comment by anderspitman** [comment]
@ErichDonGubler I could probably do more like 10-15 minutes if you'd like. 5 would be easier since it's a very simple project but I could go through more code and talk about the FFI a bit more.

**Comment by ErichDonGubler** [comment]
@anderspitman: Take as long as you'd like! :)

**Comment by anderspitman** [comment]
@ErichDonGubler I can do 15-20 minutes, or less if you prefer.
