### ISSUE TITLE
Meetup #10 content (2019-03-14)

### ISSUE THREAD

**Issue by ErichDonGubler** [utah-rust/utah-rust.github.io#23]
Meetup link: -
Utah Rust site link: -

## Current agenda

Blue sky for the agenda!

This event will be hosted at Vivint.

## Todos

- [ ] Make sure that the TWiR calendar has the Meetup link
- [ ] Create a new event page stub for this event
- [ ] Confirm venue
    - [ ] Food at venue?
    - [ ] Recording at venue?
- [ ] Ideas?
- [ ] Confirm ideas in agenda
- [ ] Have the meetup!
- [ ] Upload any videos recorded
- [ ] Edit meetup page with assets generated from meetup

**Comment by epage** [comment]
If needed, I could possibly present on https://github.com/utah-rust/utah-rust.github.io/issues/2.  I've also considered the idea of CI best practices.

Alternatively, we could look at one of the other types of content we've discussed: https://github.com/utah-rust/utah-rust.github.io/projects

**Comment by ErichDonGubler** [comment]
@epage, you are awesome. You're one of our go-to guys! :)

I feel like we've done lots of presentations in the last little while, and something to mix things up -- maybe an "Impl Days" meetup? -- would add a little spice to what we've been doing. Thoughts, everyone?

This might not necessarily preclude a presentation or two, esp. if they're short, but I wanted to see if participants wanted more of the same or if something different is interesting.

**Comment by glademiller** [comment]
I would love to attend an embedded workshop with Rust.

-- Glade

**Comment by ErichDonGubler** [comment]
^@pinealservo?

**Comment by pinealservo** [comment]
Would love to do something embedded-related! I have started catching up with recent developments and trying to figure out something concrete to present on before committing. Is there some specific aspect of embedded stuff that's of interest?

**Comment by glademiller** [comment]
For me if the most awesome thing would be to have a workshop I would be
willing to dish out some money to pay for a board of some sort and then get
walked through writing Blinky or something using Rust on that board. That
would be my dream embedded workshop since I have little to no experience
doing embedded stuff getting the hardware and software to line up is a but
intimidating.

-- Glade

**Comment by MCluck90** [comment]
I would also be up for, and willing to pay for, some kind of embedded workshop. I just barely started dipping my toes into the hardware side of things so anything in that space would be really cool to me.

**Comment by sbditto85** [comment]
If i ever get time to come i could sorta do #14 as that's what i learning and playing with right now. Even bought a book and so far its pretty good.

**Comment by sbditto85** [comment]
As for embedded I do have some old arduino boards laying around and some wires and LEDs i would happily lend if it helps.

**Comment by ErichDonGubler** [comment]
@sbditto85: #14 hasn't been done -- it was going to be done in meetup 5, but that ended up not happening. Make sure @beatgammit is okay with you stealing his thunder -- other than that, I don't see any issues with tackling it!

**Comment by creedasaurus** [comment]
Embedded stuff sounds cool, although probably over my head a bit. I'm still a newb in the Rust world. But I think I'd still totally enjoy that talk. Or any, really!

**Comment by pinealservo** [comment]
Just to temper expectations, there's no way I could put together a workshop with boards and stuff for meetup #10. I could, however, give a little intro on where the rust embedded stuff is at right now and feel out how much interest there would be in a more workshop-like thing later and what sort of hardware it would take to make it interesting.

**Comment by glademiller** [comment]
An intro would be great. It is a lot to ask to have a workshop this soon.
Ideally with the workshop people would have time to acquire hardware.

-- Glade

**Comment by ErichDonGubler** [comment]
@pinealservo: That would be fantastic. Shall I add you to the agenda?

@epage: You're good to go for a slot in the meeting if you still want it!

**Comment by pinealservo** [comment]
@ErichDonGubler Yes, you can add me.

**Comment by MCluck90** [comment]
Sorry for running away at the last minute (my fiancee had an emergency). Thank you @pinealservo for your presentation! It was awesome and informative. I'm planning to start playing around with some teensy boards and you gave me a great starting point
