### ISSUE TITLE
Meetup #13 content (2019-04-11)

### ISSUE THREAD

**Issue by ErichDonGubler** [utah-rust/utah-rust.github.io#24]
Meetup link: https://www.meetup.com/utahrust/events/258703993/
Utah Rust site link: -
Zoom meeting link: https://zoom.us/s/270507937

## Current agenda

Blue sky for agenda and venue!

## Todos

- [ ] Initial organization
    - [ ] Make sure that the Rust Community Calendar calendar has the Meetup link (for TWiR)
    - [ ] Create a new event page stub for this event
- [ ] Have the meetup!
    - [ ] Confirm venue
    - [ ] Food at venue?
    - [ ] Recording at venue?
    - [ ] Ideas?
    - [ ] Confirm ideas in agenda
- [ ] Edit Utah Rust page with assets generated from meetup
    - [ ] Outline agenda content: speakers, presentations
    - [ ] Link slides
    - [ ] Upload and link any videos recorded (@erichdongubler: Do the editing!)

**Comment by ErichDonGubler** [comment]
Hey everyone! Just wanted to give a shout-out to @CleanCut for being willing to make this meetup accessible to EVERYONE (thanks @epage for the idea). See the agenda with more details.

**Comment by epage** [comment]
Have we gathered a list of good-first-issues yet for this?

**Comment by ErichDonGubler** [comment]
Not yet -- if you could help with that, I know that `rust-cli` WG you're part of has some good ones!

**Comment by epage** [comment]
- [clap v3](https://github.com/clap-rs/clap/issues?q=is%3Aissue+is%3Aopen+v3+label%3A%22W%3A+3.x%22): probably the highest priority for the WG-CLI but one I'm least confident on providing guidance / knowing the state.
- [liquid issues](https://github.com/cobalt-org/liquid-rust/labels/good%20first%20issue): being used by cargo-generate, cargo-tarball, etc
- [cargo-generate](https://github.com/ashleygwilliams/cargo-generate/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
- [man](https://github.com/rust-cli/man/issues): for auto-generating sections of man pages
