### ISSUE TITLE
Meetup #12 content (2019-05-09)

### ISSUE THREAD

**Issue by ErichDonGubler** [utah-rust/utah-rust.github.io#28]
Meetup link: -
Zoom meeting link: -
Utah Rust site link: -

## Current agenda

The venue will be [Jane](https://www.google.com/maps/search/?api=1&query=Jane%2C+3401+N.+Thanksgiving+Way%2C+Lehi%2C+UT%2C+84043%2C+us). Thanks for hosting us, @TomPridham!

* @ErichDonGubler will be preparing a few presentations:
    * Happy Anniversary, Utah Rust!
    * Unpacking Serde
    * Using Cloudsmith as an alternative to Crates.io

## Todos

- [ ] Initial organization
    - [ ] Create a Meetup event
    - [ ] Make sure that the Rust Community Calendar calendar has the Meetup link (for TWiR)
    - [ ] Create a new event page stub for this event
- [ ] Have the meetup!
    - [ ] Confirm venue
    - [x] ~~Food at venue?~~ Yes!
    - [ ] Recording at venue?
    - [x] Ideas?
    - [x] Confirm ideas in agenda
- [ ] Edit Utah Rust page with assets generated from meetup
    - [ ] Outline agenda content: speakers, presentations
    - [ ] Link slides
    - [ ] Upload and link any videos recorded (@erichdongubler: Do the editing!)

**Comment by epage** [comment]
So the meetup says "Saturday, May 4, 2019" and this says "2019-05-09"

**Comment by ErichDonGubler** [comment]
@epage: Derp, fixed and sent out an announcement. Sorry about that!

**Comment by ErichDonGubler** [comment]
@epage: If you want to take the Serde presentation, feel free -- I thought it'd be good content to introduce this time, but I don't just want to hand it to you since you've done so much in the last few months.

**Comment by epage** [comment]
Unfortunately, I'll be out of town.

**Comment by ErichDonGubler** [comment]
No problem! I hope your travels are safe. :)

**Comment by ErichDonGubler** [comment]
Zoom link is up for those who are interested!
