### ISSUE TITLE
Meetup #13 content (2019-06-13) content

### ISSUE THREAD

**Issue by ErichDonGubler** [utah-rust/utah-rust.github.io#29]
Meetup link: -
Zoom meeting link: -
Utah Rust site link: -

## Current agenda

The venue will be the [Vivint Smart Home Innovation Center](https://www.google.com/maps/search/?api=1&query=3401+N.+Ashton+Blvd%2C+Lehi%2C+UT%2C+us). Thanks for hosting us, @adavisvivint!

* @ErichDonGubler will be preparing a second entry in what will be a series of Serde presentations.
* @epage will be preparing a presentation on real-world Serde use with examples from his own Rust projects.

## Todos

- [ ] Initial organization
    - [ ] Create a Meetup event
    - [ ] Make sure that the Rust Community Calendar calendar has the Meetup link (for TWiR)
    - [ ] Create a new event page stub for this event
- [ ] Have the meetup!
    - [x] Confirm venue
    - [x] ~~Food at venue?~~ Yes, pizza!
    - [x] Recording at venue?
    - [x] Ideas?
    - [x] Confirm ideas in agenda
- [ ] Edit Utah Rust page with assets generated from meetup
    - [ ] Outline agenda content: speakers, presentations
    - [ ] Link slides
    - [ ] Upload and link any videos recorded (@erichdongubler: Do the editing!)

**Comment by epage** [comment]
Some of the stuff  show cased

escargot for programmatically interacting with cargo
- https://github.com/crate-ci/escargot/blob/master/src/format/mod.rs
- https://github.com/crate-ci/escargot/blob/master/src/format/test.rs

cobalt for config files and content metadata
- https://github.com/cobalt-org/cobalt.rs/blob/master/src/cobalt_model/config.rs
- https://github.com/cobalt-org/cobalt.rs/blob/master/src/cobalt_model/frontmatter.rs

cargo-release for layered config
- https://github.com/sunng87/cargo-release/blob/master/src/config.rs
- https://github.com/sunng87/cargo-release/blob/master/src/main.rs

And I didn't cover stager for time and it ended up being more of the same
- https://github.com/crate-ci/stager/blob/master/src/de.rs

**Comment by epage** [comment]
And seemed like people were curious about the problem [tyypetag](https://github.com/dtolnay/typetag) solves.

**Comment by ErichDonGubler** [comment]
My slides from last night: https://docs.google.com/presentation/d/1nQxbBkHYOAXAcodVk-14th5nXhIYaOaa0cK7UG1bgxk/edit?usp=sharing
