### ISSUE TITLE
October 2019 Regular Meetup

### ISSUE THREAD

**Issue by ErichDonGubler** [utah-rust/utah-rust.github.io#35]
Meetup link: https://www.meetup.com/utah-rust/events/265465228/
Remote meeting link (no login required): https://meet.jit.si/utah-rust
Utah Rust site link: -

## Current agenda

Venue will be [Vivint Smart Home](https://www.google.com/maps/search/?api=1&query=3401+N.+Ashton+Blvd%2C+Lehi%2C+UT%2C+us). Thanks @ErichDonGubler for making that happen!

* [Rust 1.38 release](https://blog.rust-lang.org/2019/09/26/Rust-1.38.0.htmlx) happened! **This is up for grabs if somebody wants to lead the discussion on this quick topic.**
* "Unpacking Serde \#3" -- how to write your own `Deserialize` and `Serialize` trait implementations by @ErichDonGubler.

***Comment below on what you're interested in hearing about!***

## Todos

- [ ] Initial organization
    - [x] Create a Meetup event
    - [x] Make sure that the Rust Community Calendar calendar has the Meetup link (for TWiR)
    - [ ] Create a new event page stub for this event
- [x] Meetup details
    - [x] Confirm venue
    - [x] Food at venue? **Anybody want to help with this?** Send @ErichDonGubler a few bucks at [PayPal](https://paypal.me/erichdongubler) or [Venmo](https://venmo.com/erichdongubler).
    - [x] ~~Recording at venue~~ -- yes!
    - [x] Ideas?
    - [x] Confirm ideas in agenda
- [ ] Have the meetup!
- [ ] Edit Utah Rust page with assets generated from meetup
    - [ ] Outline agenda content: speakers, presentations
    - [ ] Link slides
    - [ ] Upload and link any videos recorded (@erichdongubler: Do the editing!)

**Comment by ErichDonGubler** [comment]
My slides: https://docs.google.com/presentation/d/16n62-XZ1kpF-lkb2j-jRVnaYeYWZf5EyVy4eBcs0ANc/edit?usp=sharing
